'use client'

import { useState } from 'react'
import { toast } from 'sonner'
import { Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { saveSuperAdminSettings, saveAdminSettings } from '@/lib/settings-api'
import { sanitizeText } from '@/lib/input-sanitizer'

interface LegalSettingsFormProps {
  termsConditions: string
  documentFooter: string
  workshopId: string | null
  onTermsChange: (value: string) => void
  onDocumentFooterChange: (value: string) => void
  useAdminApi?: boolean
}

export function LegalSettingsForm({
  termsConditions,
  documentFooter,
  workshopId,
  onTermsChange,
  onDocumentFooterChange,
  useAdminApi,
}: LegalSettingsFormProps) {
  const [saving, setSaving] = useState(false)

  async function handleSaveDocumentFooter() {
    if (!workshopId) return
    setSaving(true)
    try {
      const payload = { document_footer: sanitizeText(documentFooter) || null }
      if (useAdminApi) {
        await saveAdminSettings(payload)
      } else {
        await saveSuperAdminSettings(workshopId, payload)
      }
      toast.success('PDF footer saved!')
    } catch (err: any) {
      console.error('Save document footer error:', err)
      toast.error(err.message || 'Failed to save PDF footer')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-1">
        <h3 className="text-sm font-bold text-grey-dark uppercase tracking-wide">Legal & PDF Settings</h3>
        <p className="text-xs text-grey">Standard terms, conditions, and footer text for your quotes and invoices</p>
      </div>

      <div className="flex flex-col gap-5">
        <div className="flex flex-col gap-1.5">
          <label className="text-xs font-bold text-grey uppercase tracking-wide">
            Terms & Conditions
          </label>
          <textarea
            value={termsConditions}
            onChange={(e) => onTermsChange(e.target.value)}
            rows={4}
            placeholder="e.g. All quotes are valid for 30 days. Payment is due upon completion of work. Warranty: 6 months on parts and labour."
            className="w-full rounded-base border border-grey-light bg-white py-2.5 px-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/10 transition-colors text-grey-dark resize-y min-h-[100px]"
          />
          <span className="text-[10px] text-grey-medium">Appears in the Terms & Conditions section of quote and invoice PDFs.</span>
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-xs font-bold text-grey uppercase tracking-wide">
            PDF Document Footer
          </label>
          <textarea
            value={documentFooter}
            onChange={(e) => onDocumentFooterChange(e.target.value)}
            rows={3}
            placeholder="e.g. All prices include VAT. E&OE. Autofield Technics (Pty) Ltd — Reg: 2024/123456/07"
            className="w-full rounded-base border border-grey-light bg-white py-2.5 px-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/10 transition-colors text-grey-dark resize-y min-h-[80px]"
          />
          <span className="text-[10px] text-grey-medium">Displayed at the very bottom of every PDF document generated by the system.</span>
        </div>
      </div>

      <div className="flex justify-end">
        <Button
          type="button"
          onClick={handleSaveDocumentFooter}
          disabled={saving}
          aria-disabled={saving}
          className="bg-primary text-white font-bold py-2.5 px-6 rounded-base shadow-sm hover:bg-primary-dark transition-all flex items-center justify-center gap-2"
        >
          {saving ? <Loader2 size={16} className="animate-spin" /> : null}
          <span>{saving ? 'Saving...' : 'Save PDF Footer'}</span>
        </Button>
      </div>

      <div className="border-t border-grey-light pt-4">
        <p className="text-xs text-grey leading-relaxed">
          <strong>Note:</strong> Terms & Conditions are saved with your profile settings (shared across all tabs).
          The PDF Document Footer is saved separately and applied to all generated PDFs.
        </p>
      </div>
    </div>
  )
}
